title: 小瀝源野草詩社
description: 立足小瀝源的中文詩社
baseurl: ""
url: "https://yourusername.github.io"

markdown: kramdown
permalink: /:categories/:title/

collections:
  members:
    output: true
    permalink: /members/:name/
  events:
    output: true
    permalink: /events/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"

plugins:
  - jekyll-paginate
paginate: 5
