title: 小瀝源野草詩社
description: 反本質主義詩社 | Anti-Essentialism Poetry Society
baseurl: ""
url: ""
collections:
  members:
    output: true
    permalink: /members/:name/
  events:
    output: true
    permalink: /events/:year/:month/:day/:title/
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "members"
    values:
      layout: "member"
  - scope:
      path: ""
      type: "events"
    values:
      layout: "event"
markdown: kramdown